[build]
  base = "client"
  publish = "build"
  command = "npm run build"
  functions = "../netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
